export default {
  $window: window,
  $document: document,
  $html: document.documentElement,
  $body: document.body,
  $accordionList: document.querySelectorAll('.accordion__list'),
  $editionsList: document.querySelectorAll('.categories__list'),
  $headerSelect: document.querySelectorAll('.header-select'),
  $headerSubSelect: document.querySelectorAll('.header-select__subselect'),
  $headerSelectList: document.querySelectorAll('.header-select__list'),
  $headerSelectTitles: document.querySelectorAll('.header-select__top'),
  $gallerySelect: document.querySelector('.gallery-select'),
  $gallerySelectTitle: document.querySelector('.gallery-select__top'),
  $categoriesTitle: document.querySelector('.categories__title'),
  $categoriesItem: document.querySelectorAll('.categories__item'),
  $burger: document.querySelector('.burger'),
  $closeBtn: document.querySelector('.nav__close'),
  $nav: document.querySelector('.nav'),
  $searchMobile: document.querySelector('.search--mobile'),
  $flagsItems: document.querySelectorAll('.flags__item'),
  $accordionLists: document.querySelectorAll('.accordion__lists'),
  $accordionItem: document.querySelectorAll('.accordion__item'),
  $painters: document.querySelectorAll('.painter'),
  $events: document.querySelectorAll('.event'),
  $eventsShowAll: document.querySelector('.events__btn'),
}
